config/routes.rb
HandCannonCommunity::Application.routes.draw do
  devise_for :users

  match "/stores/search" => "stores#index", :as => "store_search"
  match "/stores/pending" => "stores#pending", :as => "pending_stores"
  match "/stores/approve/:id" => "stores#approve", :as => "approve_store"
  match "/stores/manage" => "stores#manage", :as => "manage_stores"
  resources :stores
  
  devise_for :users, :controllers => { :registrations => 'user_registrations'}
  scope "/admin" do 
    resources :users
  end
  
  root  :to =>"stores#index"

end

app/models/store.rb
class Store < ActiveRecord::Base  
  class GeolocException < Exception
  end
  acts_as_mappable
  has_and_belongs_to_many :game_systems
  before_validation :address_extra_fields_store
  after_validation :give_latlng_errors_to_address, :if => lambda{ |obj| obj.address_changed? }
  
  validates_presence_of :name, :description, :address, :phone_number
  validates_numericality_of :lat, :greater_than_or_equal_to => -90, :less_than_or_equal_to => 90
  validates_numericality_of :lng, :greater_than_or_equal_to => -180, :less_than_or_equal_to => 180
  validates_uniqueness_of :lat, :scope => :lng, :message => "must be a unique location"
  validates_uniqueness_of :address #should I add email and phone_number?
  
  attr_accessible :name, :address, :email, :phone_number, :description, :hours, :url, :online_store_url, :game_system_ids
  
  scope :approved, where(:approved => true)
  scope :unapproved, where(:approved => false)
  
  def address_extra_fields_store
      loc = Geokit::Geocoders::GoogleGeocoder.geocode(address)
      if loc and loc.success
        self.lat = loc.lat.to_f
        self.lng = loc.lng.to_f
        if not loc.state.empty?
          self.state = loc.state
        elsif not loc.province.empty?
          self.sate = loc.province
        end
        self.country = loc.country_code
      else
        errors.add(:address, "Unable to find address, please verify that it is correct and can be found on google maps")
      end
  end
  
  def give_latlng_errors_to_address
    [:lat, :lng].each do |field|
      errors[field].each do |error|
        errors.add(:address, error)
      end
      errors[field].clear
    end
  end  
  
  def self.search(search)
    stores = self.approved
    if search.near and not search.near.empty?
      stores = stores.near(search.near)
    end
    if search.game_systems
      stores = stores.joins(:game_systems).where(:game_systems => {:id => search.game_systems})
      stores = stores.group('stores.id, stores.name, stores.address, stores.lat, stores.lng, stores.email, stores.phone_number, stores.description, stores.hours, stores.approved, stores.url, stores.created_at, stores.updated_at, stores.online_store_url, stores.country, stores.state')
      #the above feels like a hack, but is necessary for the time being
    end
    stores
  end
  
  def self.near(location, distance = 0)
    distance = 50 unless distance > 0
    stores = Store.approved.within(distance, :origin => find_origin(location) )
    if stores.count == 0
      raise GeolocException, "Unable to find any stores near that location, please check your spelling and try again"
    else
      stores
    end
  end
  
  private
  def self.find_origin(location)
    loc = Geokit::Geocoders::GoogleGeocoder.geocode(location)
    if loc.success
      [loc.lat, loc.lng]
    else
      raise GeolocException, "Unable to find location, please check your spelling and try again"
    end
  end
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  respond_to :html, :xml, :json, :js
  load_resource :only => [:show, :new, :create]
  load_and_authorize_resource :except => [:show, :new, :create, :index]
  
  # GET /stores
  # GET /stores.xml
  # This method requires custom resource loading
  def index
    begin
      @search = StoreSearch.new(params[:store_search] || {})
      @stores = Store.search(@search)
    rescue Store::GeolocException => e
      flash.now[:warning] = e.message
      params[:store_search].delete :near
      @search = StoreSearch.new(params[:store_search])
      @stores = Store.search(@search)
    end

    respond_with(@stores)
  end
  
  def pending
    @pending = @stores.unapproved    
    
    respond_with(@pending)
  end
  
  def manage #may need to paginate later
  end

  # GET /stores/1
  # GET /stores/1.xml
  def show
    respond_with(@store)
  end

  # GET /stores/new
  # GET /stores/new.xml
  def new
    respond_with(@store)    
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.xml
  def create
    if can? :manage, @store
      @store.approved = true      
    end

    respond_to do |format|
      if @store.save
        msg = ''
        unless @store.approved
          msg = ', an administrator will need to approve it'
        end
        format.html { redirect_to(root_url, :notice => "Store was successfully created#{msg}.") }
        format.xml  { render :xml => @store, :status => :created, :location => @store }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @store.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.xml
  def update
    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to(@store, :notice => 'Store was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @store.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.xml
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to(stores_url) }
      format.xml  { head :ok }
    end
  end  
  
  def approve
    @store.approved = true
    @store.save
    
    respond_to do |format|
      format.html { redirect_to(pending_stores_url) }
    end
  end
  
  
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<% lable_text = lambda {|value, required| "#{required} #{value} #{content_tag :br}"}%>

<%= simple_form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input">
    <div class="fieldgroup">
      <fieldset class="flow">
        <legend>Location Information</legend>
      <%= f.input :name, :label_text => lable_text %>
      <%= f.input :address %>
      <%= f.input :url %>
      <%= f.input :online_store_url %>
    </fieldset>
      
      <fieldset class="flow">
        <legend>Contact Information</legend>
      <%= f.input :phone_number %>
      <%= f.input :email %>
    </fieldset>
    </div>
    
    <div class="fieldgroup">
      <fieldset class="divider even">
        <%= f.association :game_systems, :as => :check_boxes %>        
      </fieldset>
    </div>
    
    <div class="fieldgroup">
      <fieldset class="flow">
        <%= f.input :hours, :as => :text %>
      </fieldset>
      
      <fieldset class="flow">
        <%= f.input :description, :as => :text %>
      </fieldset>
    </div>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stores/_map.html.erb
<%content_for :head do%>
<%= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.3&sensor=false" %>
<%= javascript_include_tag 'gmap/markermanager.js', 'gmap/StyledMarker.js', 'gmap/markerclusterer' %>
<%= javascript_include_tag "jquery.metadata.2.1/jquery.metadata.js" %>
<%= javascript_include_tag "jquery.jmapping-2.1.0/jquery.jmapping.js" %>
<%= javascript_include_tag "map" %>
<%= stylesheet_link_tag "map" %>
<%end%>

  <div id="map"></div>
  
  <%= render :partial => "search" %>
  
  <div id="map-side-bar">
    <%= render :partial => "map_sidebar" %>
  </div>

app/views/stores/_map_guts.erb
<div id="map"></div>

<div id="map-side-bar">
<% @stores.each do |store| %>
  <div class="map-location" data-jmapping="{id: <%= store.id %>, point: {lat: <%= store.lat %>, lng: <%= store.lng %>}}">
    <a href="#" class="map-link"><%= store.name %></a>
    <div class="info-box">
      <p><%= store.description %></p>
    </div>
  </div>
<% end %>
</div>

app/views/stores/_map_sidebar.erb
<% @stores.each do |store| %>
  <div id="store-<%=store.id%>" class="map-location" data-jmapping="{id: <%=store.id%>, point: {lat: <%= store.lat %>, lng: <%= store.lng %>}}">
    <a href="#" class="map-link"><%= store.name %></a>
    <div class="info-box">
      <%= render store, :summary => true %>
    </div>
  </div>
<% end %>

app/views/stores/_search.html.erb
<div id="search">
<%= simple_form_for @search, :url => store_search_path, :remote => true, :method => :get do |f| %>
<%= f.input :near, :label => "Search for stores near" %>
<label>and carrying the following game systems</label>
<ul>
<%= f.collection_check_boxes :game_systems, 
@search.available_game_systems, :id, :name, 
:checked => @search.game_systems.map{|gs| gs.id},
:item_wrapper_tag => :li,
:label_text => lambda { |label, required| content_tag :span, label } 
%>
</ul>


<%= f.button :submit, "Search For Stores" %>
<%end%>

<br />

<div class="recommend_button">
<%= link_to 'Recommend a new store', new_store_path %>
</div>

</div>

app/views/stores/_store.erb
<h3><%= link_to store.name, store.url %></h3>
<p><%= store.address%></p>
<p>Phone: <%= store.phone_number%></p>
<p>Email: <a href="mailto:<%=store.email%>"><%=store.email%></a></p>
<% if summary %>
<p><%= link_to "View Full Details", store_path(store) %></p>
<% else %>
<p><%= simple_format store.hours %></p>
<p><%= simple_format store.description %></p>
<% end %>

<ul class="game_systems">
<% store.game_systems.each do |game| %>
  <li>carries <%= game.name %></li>
<% end %>
</ul>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<%= render :partial => "map", :stores => @stores %>

app/views/stores/index.js.erb
{
"map_sidebar": "<%= escape_javascript(render(:partial => 'map_sidebar')) %>",
"errors": "<%= escape_javascript(render(:partial => 'layouts/errors')) %>"
}

app/views/stores/manage.html.erb
<div class="stores_edit">
<% @stores.each do |store| %>
<div id="store-<%=store.id%>" class="store">
  <%= render store, :summary => true %>
  <%= link_to "Edit", edit_store_path(store) %>
  <%= link_to "Delete", store_path(store), :method => :delete %>
</div>
<%end%>
</div>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/pending.html.erb
<div class="pending-stores">
<% @pending.each do |store| %>
  <div class ="store"><%= render store, :summary => false %>
      <%= link_to "Approve", approve_store_path(store) %> |
      <%= link_to "Edit", edit_store_path(store) %> |
      <%= link_to "Delete", store_path(store), :method => :delete, :confirm => "Are you sure?" %> 
  </div>
<% end%>
</div>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @store, :summary => false %>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>