config/routes.rb
HandCannonCommunity::Application.routes.draw do
  devise_for :users

  match "/stores/search" => "stores#index", :as => "store_search"
  match "/stores/pending" => "stores#pending", :as => "pending_stores"
  match "/stores/approve/:id" => "stores#approve", :as => "approve_store"
  match "/stores/manage" => "stores#manage", :as => "manage_stores"
  resources :stores
  
  devise_for :users, :controllers => { :registrations => 'user_registrations'}
  scope "/admin" do 
    resources :users
  end
  
  root  :to =>"stores#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_dashboard.html.erb
<div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>.
          <%= link_to "Sign out", destroy_user_session_path %>
        <% else %>
          <%= link_to "sign in", new_user_session_path %>
        <% end %>

      <ul>
        <li>
          <a title="Home" href="http://handcannononline.com/">Home</a>
        </li>
        <li>
          <a title="About" href="http://handcannononline.com/about/">About</a>
        </li>
        <li>
          <a title="Events Calendar" href="http://handcannononline.com/events-calendar/">Events Calendar</a>
        </li>
        <li>
          <a title="Hand Cannon E-Zine" href="http://handcannononline.com/handcannon-ezine/">Hand Cannon E-Zine</a>
        </li>
        <li>
          <a title="Gaming Resources" href="http://handcannononline.com/73-2/">Gaming Resources</a>
        </li>
        <li><%= link_to "Store Map", stores_path %></li>
          <% if can? :manage, User %>
            <li><%= link_to "Manage Users", users_path%></li>  
          <% end %>
          
          <% if can? :manage, Store %>
            <li><%= link_to "Stores Pending Approval(#{pending_store_count})", pending_stores_path%></li>
            <li><%= link_to "Manage Stores", manage_stores_path %>
          <% end %>
          
          <% if can? :update, current_user %>
          <li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
          <% end %>
      </ul>
</div>

app/views/layouts/_errors.erb
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Hand Cannon Community" %></title>
    <%= stylesheet_link_tag "application", "jquery.jnotify" %>
    <%= javascript_include_tag :defaults, "jquery.jnotify", "error_popups", "selectivizr" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
    <link rel="shortcut icon" href="http://handcannononline.com/favicon.ico" />
    <link rel="icon" type="image/vnd.microsoft.icon" href="http://handcannononline.com/favicon.ico" />
  </head>
  <body>
    <div id="container">
      <div id="content-header">
        <div class="logo">
          <h1><a href="http://handcannononline.com">Hand Cannon Online</a></h1>
        </div>
        <div id="flash">
          <%= render "layouts/errors"%>
        </div>
        
        <%= render "layouts/dashboard" %>
      </div>
      
      
      
      <%#= content_tag :h1, yield(:title) if show_title? %>
      <div id="content-body">
        <%= yield %>
      </div>    
    </div>
  </body>
</html>